<h1>Olá, Rodrigo</h1>

<?php $this->headTitle("Blog"); ?>

<p><a class="btn btn-default" href="<?php echo $this->url('post', ['action' => 'add']);?>">Adicionar</a></p>

<table class="table">
    <tr>
        <th>Post</th>
        <th>Content</th>
        <th>Actions</th>
    </tr>
    <?php foreach ($posts as $post) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($post->title); ?></td>
            <td><?php echo $this->escapeHtml($post->content); ?></td>
            <td>
                <a href="<?php echo $this->url('post', ['action' => 'edit' , 'id' => $post->id]);?>" class='btn btn-info'>Editar</a>
                <a href="<?php echo $this->url('post', ['action' => 'delete' , 'id' => $post->id]);?>" class="btn btn-danger">Remover</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>